@extends('admin.admin_master')
@section('admin')
<div class="page-content"><div class="container-fluid">
    <div class="page-title-box"><h4>Demand Forecast</h4><p class="text-muted">Historical average with optional planner override and 95% variability band.</p></div>
    <div class="card mb-3"><div class="card-body"><form class="row g-2 align-items-end"><div class="col-md-2"><label>History days</label><input name="history_days" type="number" min="7" max="730" value="{{ $historyDays }}" class="form-control"></div><div class="col-md-2"><label>Forecast horizon days</label><input name="horizon_days" type="number" min="1" max="365" value="{{ $horizonDays }}" class="form-control"></div><div class="col-md-3"><label>Location (optional)</label><select name="location_id" class="form-select"><option value="">All locations</option>@foreach($locations as $location)<option value="{{ $location->id }}" @selected((string) $locationId === (string) $location->id)>{{ $location->warehouse->name }} / {{ $location->code }}</option>@endforeach</select></div><div class="col-md-3"><label>Forecast model</label><select name="seasonality" class="form-select"><option value="none" @selected($seasonality === 'none')>Flat average</option><option value="weekly" @selected($seasonality === 'weekly')>Weekly pattern</option><option value="auto" @selected($seasonality === 'auto')>Automatic selection</option></select></div><div class="col-md-2"><button class="btn btn-primary">Forecast</button></div></form><small class="text-muted">{{ $locationId ? 'Location ledger demand' : 'Approved sales history' }}: {{ $from }} through {{ $to }} ({{ $seasonality }})</small></div></div>
    <div class="card"><div class="card-body table-responsive"><table class="table table-bordered"><thead><tr><th>Product</th><th>Historical sold</th><th>Daily rate</th><th>Forecast</th><th>95% band</th><th>Current stock</th><th>Projected balance</th><th>Override</th></tr></thead><tbody>
    @forelse($forecasts as $row)
        <tr><td>{{ $row['product']->name }}</td><td>{{ number_format($row['historical_qty'], 3) }}</td><td>{{ number_format($row['daily_rate'], 3) }}</td><td>{{ number_format($row['forecast_qty'], 3) }} @if($row['override'])<span class="badge bg-info">Override</span>@endif</td><td>{{ number_format($row['confidence_low'], 3) }} – {{ number_format($row['confidence_high'], 3) }}</td><td>{{ number_format($row['location_id'] ? $row['projected_balance'] + $row['forecast_qty'] : $row['product']->quantity, 3) }}</td><td class="{{ $row['projected_balance'] <= $row['reorder_level'] ? 'text-danger fw-bold' : '' }}">{{ number_format($row['projected_balance'], 3) }}</td><td><form method="POST" action="{{ route('planning.demand.forecast.override') }}" class="d-flex gap-1">@csrf<input type="hidden" name="product_id" value="{{ $row['product']->id }}"><input type="hidden" name="location_id" value="{{ $locationId }}"><input type="hidden" name="period_start" value="{{ $forecastFrom }}"><input type="hidden" name="period_end" value="{{ $forecastTo }}"><input name="forecast_quantity" type="number" min="0" step="0.001" class="form-control form-control-sm" style="width:95px" value="{{ number_format($row['forecast_qty'], 3, '.', '') }}" title="Forecast quantity"><button class="btn btn-sm btn-outline-primary">Save</button></form></td></tr>
    @empty
        <tr><td colspan="8" class="text-center">No sales history or low-stock products found.</td></tr>
    @endforelse
    </tbody></table></div></div>
</div></div>
@endsection
