@extends('admin.admin_master')
@section('admin')
<div class="container-fluid mt-3">
    <div class="d-flex justify-content-between align-items-center mb-3"><div><h4>Dispatch Manifests</h4><p class="text-muted mb-0">Group dispatched deliveries for carrier handoff.</p></div></div>
    @if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
    @if(session('message'))<div class="alert alert-{{ session('alert-type', 'success') }}">{{ session('message') }}</div>@endif
    <form method="post" action="{{ route('warehouse.dispatch-manifests.store') }}">
        @csrf
        <div class="card mb-3"><div class="card-header d-flex justify-content-between"><span>Eligible dispatched deliveries ({{ $eligibleDeliveries->count() }})</span><button class="btn btn-primary btn-sm">Create planned manifest</button></div><div class="table-responsive"><table class="table table-hover mb-0"><thead><tr><th></th><th>Delivery</th><th>Date</th><th>Customer</th><th>Carrier/service</th><th>Quote</th><th>Packages</th></tr></thead><tbody>@forelse($eligibleDeliveries as $delivery)<tr><td><input type="checkbox" name="delivery_ids[]" value="{{ $delivery->id }}" checked></td><td>{{ $delivery->delivery_no }}</td><td>{{ optional($delivery->date)->toDateString() }}</td><td>{{ $delivery->salesOrder?->customer?->name ?: '—' }}</td><td>{{ $delivery->carrier ?: '—' }}@if($delivery->carrier_service_code)<br><small>{{ $delivery->carrier_service_code }}</small>@endif</td><td>@if($delivery->carrier_quote_amount !== null){{ $delivery->carrier_quote_currency }} {{ number_format((float) $delivery->carrier_quote_amount, 2) }}@else—@endif</td><td>{{ $delivery->packages->count() }}</td></tr>@empty<tr><td colspan="7" class="text-center text-muted">No eligible dispatched deliveries.</td></tr>@endforelse</tbody></table></div><div class="card-body row g-2"><div class="col-md-3"><label class="form-label">Carrier</label><input name="carrier" class="form-control" maxlength="255"></div><div class="col-md-3"><label class="form-label">Tracking reference</label><input name="tracking_reference" class="form-control" maxlength="255"></div><div class="col-md-3"><label class="form-label">Manifest date</label><input name="manifest_date" type="date" value="{{ now()->toDateString() }}" class="form-control"></div><div class="col-md-3"><label class="form-label">External reference</label><input name="external_reference" class="form-control" maxlength="150"></div></div></div>
    </form>
    <div class="card"><div class="card-header">Recent manifests</div><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Manifest</th><th>Carrier</th><th>Status</th><th>Deliveries</th><th>Actions</th></tr></thead><tbody>@forelse($manifests as $manifest)<tr><td>{{ $manifest->manifest_no }}</td><td>{{ $manifest->carrier ?: '—' }}</td><td>{{ ucfirst(str_replace('_', ' ', $manifest->status)) }}</td><td>{{ $manifest->deliveries->count() }}</td><td class="d-flex gap-1">@if($manifest->status === 'planned')<form method="post" action="{{ route('warehouse.dispatch-manifests.handoff', $manifest->id) }}">@csrf<button class="btn btn-sm btn-success">Handoff</button></form><form method="post" action="{{ route('warehouse.dispatch-manifests.cancel', $manifest->id) }}">@csrf<input type="hidden" name="cancellation_reason" value="Cancelled by warehouse operator"><button class="btn btn-sm btn-outline-danger">Cancel</button></form>@elseif($manifest->status === 'handed_off')<form method="post" action="{{ route('warehouse.dispatch-manifests.close', $manifest->id) }}">@csrf<button class="btn btn-sm btn-outline-primary">Close</button></form>@endif</td></tr>@empty<tr><td colspan="5" class="text-center text-muted">No manifests created.</td></tr>@endforelse</tbody></table></div><div class="card-footer">{{ $manifests->links() }}</div></div>
</div>
@endsection
