@extends('admin.admin_master')
@section('admin')
<div class="page-content"><div class="container-fluid">
<div class="page-title-box"><h4>Customer Contacts &amp; Addresses</h4></div>
<div class="card mb-3"><div class="card-body"><form method="POST" action="{{ route('customer.contacts.store') }}" class="row g-2">@csrf
<div class="col-md-2"><select name="customer_id" class="form-select" required><option value="">Customer</option>@foreach($customers as $customer)<option value="{{ $customer->id }}">{{ $customer->name }}</option>@endforeach</select></div>
<div class="col-md-2"><select name="contact_type" class="form-select" required><option value="shipping">Shipping</option><option value="billing">Billing</option><option value="contact">Contact</option></select></div><div class="col-md-2"><input name="contact_name" class="form-control" placeholder="Contact name"></div><div class="col-md-2"><input name="phone" class="form-control" placeholder="Phone"></div><div class="col-md-2"><input name="email" type="email" class="form-control" placeholder="Email"></div><div class="col-md-2"><input name="label" class="form-control" placeholder="Label"></div>
<div class="col-md-4"><input name="line1" class="form-control" placeholder="Address line 1"></div><div class="col-md-3"><input name="line2" class="form-control" placeholder="Address line 2"></div><div class="col-md-2"><input name="city" class="form-control" placeholder="City"></div><div class="col-md-2"><input name="state" class="form-control" placeholder="State"></div><div class="col-md-1"><input name="postal_code" class="form-control" placeholder="PIN"></div><div class="col-md-1"><input name="country" value="IN" maxlength="2" class="form-control" placeholder="CC"></div><div class="col-md-1 form-check ms-2"><input name="is_default" value="1" type="checkbox" class="form-check-input" id="customer-contact-default"><label for="customer-contact-default" class="form-check-label">Default</label></div><div class="col-md-2"><button class="btn btn-primary">Save contact</button></div></form></div></div>
<div class="card"><div class="card-body"><div class="table-responsive"><table class="table table-bordered"><thead><tr><th>Customer</th><th>Type</th><th>Contact</th><th>Phone/email</th><th>Address</th><th>Default</th><th>Actions</th></tr></thead><tbody>@forelse($contacts as $contact)
<tr><td>{{ data_get($contact, 'customer.name', 'N/A') }}</td><td>{{ ucfirst($contact->contact_type) }}</td><td>{{ $contact->contact_name ?: '—' }}</td><td>{{ $contact->phone ?: '—' }}<br>{{ $contact->email ?: '' }}</td><td>{{ implode(', ', array_filter([$contact->line1, $contact->line2, $contact->city, $contact->state, $contact->postal_code])) }}</td><td>{{ $contact->is_default ? 'Yes' : 'No' }}</td><td><details><summary class="btn btn-sm btn-outline-secondary">Edit</summary>
<form method="POST" action="{{ route('customer.contacts.update', $contact->id) }}" class="row g-2 mt-2">@csrf @method('PATCH')
<div class="col-12"><select name="contact_type" class="form-select form-select-sm" required><option value="shipping" @selected($contact->contact_type === 'shipping')>Shipping</option><option value="billing" @selected($contact->contact_type === 'billing')>Billing</option><option value="contact" @selected($contact->contact_type === 'contact')>Contact</option></select></div><div class="col-12"><input name="label" value="{{ $contact->label }}" class="form-control form-control-sm" placeholder="Label"></div><div class="col-12"><input name="contact_name" value="{{ $contact->contact_name }}" class="form-control form-control-sm" placeholder="Contact name"></div><div class="col-12"><input name="phone" value="{{ $contact->phone }}" class="form-control form-control-sm" placeholder="Phone"></div><div class="col-12"><input name="email" value="{{ $contact->email }}" type="email" class="form-control form-control-sm" placeholder="Email"></div><div class="col-12"><input name="line1" value="{{ $contact->line1 }}" class="form-control form-control-sm" placeholder="Address line 1"></div><div class="col-12"><input name="line2" value="{{ $contact->line2 }}" class="form-control form-control-sm" placeholder="Address line 2"></div><div class="col-6"><input name="city" value="{{ $contact->city }}" class="form-control form-control-sm" placeholder="City"></div><div class="col-6"><input name="state" value="{{ $contact->state }}" class="form-control form-control-sm" placeholder="State"></div><div class="col-6"><input name="postal_code" value="{{ $contact->postal_code }}" class="form-control form-control-sm" placeholder="PIN"></div><div class="col-6"><input name="country" value="{{ $contact->country ?: 'IN' }}" maxlength="2" class="form-control form-control-sm" placeholder="CC"></div><div class="col-12 form-check"><input name="is_default" value="1" type="checkbox" class="form-check-input" id="contact-default-{{ $contact->id }}" @checked($contact->is_default)><label for="contact-default-{{ $contact->id }}" class="form-check-label">Default</label></div><div class="col-12"><button class="btn btn-sm btn-primary">Update</button></div></form></details></td></tr>
@empty<tr><td colspan="7" class="text-center">No customer contacts found.</td></tr>@endforelse</tbody></table></div>{{ $contacts->links() }}</div></div></div></div>
@endsection
