@extends('admin.admin_master')
@section('admin')
<div class="page-content"><div class="container-fluid">
    <div class="page-title-box"><h4>Sales Report</h4><p class="text-muted">Approved sales by product and customer.</p></div>
    <div class="card mb-3"><div class="card-body"><form method="GET" action="{{ route('reports.sales') }}" class="row g-2"><div class="col-md-2"><label class="form-label">From</label><input type="date" name="from" value="{{ $from }}" class="form-control"></div><div class="col-md-2"><label class="form-label">To</label><input type="date" name="to" value="{{ $to }}" class="form-control"></div><div class="col-md-3"><label class="form-label">Product</label><select name="product_id" class="form-select"><option value="">All products</option>@foreach($products as $product)<option value="{{ $product->id }}" @selected((string) request('product_id') === (string) $product->id)>{{ $product->name }}</option>@endforeach</select></div><div class="col-md-3"><label class="form-label">Customer</label><select name="customer_id" class="form-select"><option value="">All customers</option>@foreach($customers as $customer)<option value="{{ $customer->id }}" @selected((string) request('customer_id') === (string) $customer->id)>{{ $customer->name }}</option>@endforeach</select></div><div class="col-md-2 d-flex align-items-end"><button class="btn btn-primary w-100">Filter</button></div></form></div></div>
    <div class="row g-2 mb-3">@foreach([['Documents', $summary['documents']], ['Return documents', $summary['return_documents']], ['Quantity', number_format($summary['quantity'], 3)], ['Revenue', number_format($summary['revenue'], 2)], ['Gross profit', number_format($summary['gross_profit'], 2)]] as $metric)<div class="col-md-3"><div class="card mb-0"><div class="card-body"><small class="text-muted">{{ $metric[0] }}</small><h5 class="mb-0">{{ $metric[1] }}</h5></div></div></div>@endforeach</div>
    <div class="card"><div class="card-body"><div class="table-responsive"><table class="table table-bordered"><thead><tr><th>Product</th><th>Customer</th><th>Documents</th><th>Return documents</th><th>Quantity</th><th>Revenue</th><th>Tax</th><th>COGS</th><th>Gross profit</th><th>Margin</th></tr></thead><tbody>
    @forelse($rows as $row)<tr><td>{{ $row['product']?->name ?? 'Unknown' }}</td><td>{{ $row['customer']?->name ?? 'Walk-in' }}</td><td>{{ $row['documents'] }}</td><td>{{ $row['return_documents'] }}</td><td>{{ number_format($row['quantity'], 3) }}</td><td>{{ number_format($row['revenue'], 2) }}</td><td>{{ number_format($row['tax'], 2) }}</td><td>{{ number_format($row['cogs'], 2) }}</td><td>{{ number_format($row['gross_profit'], 2) }}</td><td>{{ $row['revenue'] > 0 ? number_format($row['gross_profit'] / $row['revenue'] * 100, 2).'%' : '0.00%' }}</td></tr>@empty<tr><td colspan="10" class="text-center">No approved sales found for this period.</td></tr>@endforelse
    </tbody></table></div></div></div>
</div></div>
<div class="mt-2"><form method="GET" action="{{ route('reports.sales.export') }}" class="d-inline">@foreach(['from', 'to', 'product_id', 'customer_id'] as $filter)<input type="hidden" name="{{ $filter }}" value="{{ request($filter) }}">@endforeach<button class="btn btn-outline-secondary btn-sm">Export CSV</button></form></div>
@endsection
