@extends('admin.admin_master')
@section('admin')
<div class="page-content"><div class="container-fluid">
    <div class="page-title-box"><h4>Product Attributes &amp; Variants</h4><p class="text-muted">Create reusable attribute values and variant SKUs under a parent product.</p></div>
    <div class="row">
        <div class="col-lg-5">
            <div class="card mb-3"><div class="card-body"><h5>Create attribute</h5><form method="POST" action="{{ route('product.attributes.store') }}">@csrf<div class="mb-2"><input name="name" class="form-control" placeholder="Attribute name (e.g. Color)" required></div><div class="mb-2"><input name="value" class="form-control" placeholder="First value (e.g. Red)" required></div><button class="btn btn-primary">Create attribute</button></form></div></div>
            <div class="card mb-3"><div class="card-body"><h5>Add attribute value</h5><form method="POST" action="{{ route('product.attributes.values.store') }}">@csrf<select name="attribute_id" class="form-select mb-2" required><option value="">Attribute</option>@foreach($attributes as $attribute)<option value="{{ $attribute->id }}">{{ $attribute->name }}</option>@endforeach</select><input name="value" class="form-control mb-2" placeholder="Value" required><button class="btn btn-light">Save value</button></form></div></div>
            <div class="card"><div class="card-body"><h5>Create variant</h5><form method="POST" action="{{ route('product.variants.store') }}">@csrf<select name="parent_product_id" class="form-select mb-2" required><option value="">Parent product</option>@foreach($parents as $parent)<option value="{{ $parent->id }}">{{ $parent->name }}</option>@endforeach</select><input name="name" class="form-control mb-2" placeholder="Variant name" required><input name="sku" class="form-control mb-2" placeholder="Variant SKU"><input name="barcode" class="form-control mb-2" placeholder="Variant barcode"><div class="row g-2 mb-2"><div class="col"><input name="purchase_price" type="number" step="0.000001" min="0" class="form-control" placeholder="Purchase price"></div><div class="col"><input name="sales_price" type="number" step="0.000001" min="0" class="form-control" placeholder="Sales price"></div><div class="col"><input name="tax_rate" type="number" step="0.0001" min="0" max="100" class="form-control" placeholder="Tax %"></div></div><div class="row g-2 mb-2"><div class="col"><select name="lifecycle_status" class="form-select"><option value="active">Active</option><option value="draft">Draft</option><option value="discontinued">Discontinued</option><option value="blocked">Blocked</option><option value="archived">Archived</option></select></div><div class="col form-check mt-2"><input name="can_purchase" value="1" type="checkbox" class="form-check-input" id="variant_can_purchase" checked><label class="form-check-label" for="variant_can_purchase">Purchasable</label></div><div class="col form-check mt-2"><input name="can_sell" value="1" type="checkbox" class="form-check-input" id="variant_can_sell" checked><label class="form-check-label" for="variant_can_sell">Sellable</label></div></div>@foreach($attributes as $attribute)<label class="form-label mb-0">{{ $attribute->name }}</label><select name="attribute_value_id[]" class="form-select mb-2"><option value="">Not set</option>@foreach($attribute->values as $value)<option value="{{ $value->id }}">{{ $value->value }}</option>@endforeach</select>@endforeach<button class="btn btn-success">Create variant</button></form></div></div>
        </div>
        <div class="col-lg-7"><div class="card"><div class="card-body"><div class="table-responsive"><table class="table table-bordered"><thead><tr><th>Variant</th><th>Parent</th><th>SKU</th><th>Attributes</th><th>Stock</th></tr></thead><tbody>@forelse($variants as $variant)<tr><td>{{ $variant->name }}</td><td>{{ $variant->parentProduct->name }}</td><td>{{ $variant->sku ?? '—' }}</td><td>@foreach($variant->attributeAssignments as $assignment)<span class="badge bg-light text-dark me-1">{{ $assignment->attribute->name }}: {{ $assignment->value->value }}</span>@endforeach</td><td>{{ $variant->quantity }}</td></tr>@empty<tr><td colspan="5" class="text-center">No variants.</td></tr>@endforelse</tbody></table></div>{{ $variants->links() }}</div></div></div>
    </div>
</div></div>
<div class="container-fluid mt-3"><div class="card"><div class="card-body"><h5>Update variant overrides</h5>@foreach($variants as $variant)<form method="POST" action="{{ route('product.variants.update', $variant->id) }}" class="border-bottom py-3">@csrf @method('PATCH')<div class="row g-2 align-items-end"><div class="col-md-2"><label class="form-label">Variant</label><input name="name" class="form-control" value="{{ $variant->name }}" required></div><div class="col-md-1"><label class="form-label">SKU</label><input name="sku" class="form-control" value="{{ $variant->sku }}"></div><div class="col-md-1"><label class="form-label">Purchase</label><input name="purchase_price" type="number" step="0.000001" min="0" class="form-control" value="{{ $variant->purchase_price }}"></div><div class="col-md-1"><label class="form-label">Sales</label><input name="sales_price" type="number" step="0.000001" min="0" class="form-control" value="{{ $variant->sales_price }}"></div><div class="col-md-1"><label class="form-label">Tax %</label><input name="tax_rate" type="number" step="0.0001" min="0" max="100" class="form-control" value="{{ $variant->tax_rate }}"></div><div class="col-md-2"><label class="form-label">Lifecycle</label><select name="lifecycle_status" class="form-select">@foreach(['draft','active','discontinued','blocked','archived'] as $state)<option value="{{ $state }}" @selected(($variant->lifecycle_status ?: 'active') === $state)>{{ ucfirst($state) }}</option>@endforeach</select></div><div class="col-md-1 form-check"><input name="can_purchase" value="1" type="checkbox" class="form-check-input" id="purchase_{{ $variant->id }}" @checked($variant->can_purchase ?? true)><label class="form-check-label" for="purchase_{{ $variant->id }}">Buy</label></div><div class="col-md-1 form-check"><input name="can_sell" value="1" type="checkbox" class="form-check-input" id="sell_{{ $variant->id }}" @checked($variant->can_sell ?? true)><label class="form-check-label" for="sell_{{ $variant->id }}">Sell</label></div><div class="col-md-1"><button class="btn btn-outline-primary">Update</button></div></div></form>@endforeach</div></div></div>
@endsection
