@extends('admin.admin_master')
@section('admin')
<div class="container-fluid"><div class="row g-3 mb-3"><div class="col-md-3"><label class="form-label">Store</label><select id="order-store" class="form-select"><option value="">No store</option>@foreach($stores as $store)<option value="{{ $store->id }}" @selected(old('store_id') == $store->id)>{{ $store->name }} ({{ $store->branch->name }})</option>@endforeach</select></div></div></div>
<div class="page-content"><div class="container-fluid"><div class="page-title-box"><h4>New Sales Order</h4><p class="text-muted">Quantities are normalized to the product stock unit.</p></div><div class="card"><div class="card-body"><form method="POST" action="{{ route('fulfillment.orders.store') }}">@csrf
<div class="row g-3 mb-3"><div class="col-md-3"><label class="form-label">Order no.</label><input name="order_no" value="{{ old('order_no', 'SO-'.now()->format('YmdHis')) }}" class="form-control" required></div><div class="col-md-3"><label class="form-label">Customer</label><select name="customer_id" class="form-select" required><option value="">Select customer</option>@foreach($customers as $customer)<option value="{{ $customer->id }}" @selected(old('customer_id', $selectedCustomerId) == $customer->id)>{{ $customer->name }}</option>@endforeach</select></div><div class="col-md-3"><label class="form-label">Fulfillment location</label><select name="location_id" class="form-select"><option value="">Any authorized location</option>@foreach($locations as $location)<option value="{{ $location->id }}" @selected(old('location_id') == $location->id)>{{ $location->code }}</option>@endforeach</select></div><div class="col-md-3"><label class="form-label">Date</label><input type="date" name="date" value="{{ old('date', now()->toDateString()) }}" class="form-control" required></div></div>
<div class="row g-3 mb-3"><div class="col-md-3"><label class="form-label">Requested date</label><input type="date" name="requested_date" value="{{ old('requested_date') }}" class="form-control"></div><div class="col-md-3"><label class="form-label">Promotion code</label><input name="promotion_code" value="{{ old('promotion_code') }}" maxlength="80" class="form-control"></div><div class="col-md-3"><label class="form-label">Description</label><textarea name="description" class="form-control">{{ old('description') }}</textarea></div><div class="col-md-3 d-flex align-items-end"><div class="form-check"><input type="checkbox" name="allow_backorders" value="1" class="form-check-input" id="allow-backorders" @checked(old('allow_backorders'))><label class="form-check-label" for="allow-backorders">Allow backorders</label></div></div></div>
<div class="table-responsive"><table class="table" id="so-lines"><thead><tr><th>Product</th><th>UOM</th><th>Quantity</th><th>Unit price</th><th>Discount</th><th></th></tr></thead><tbody><tr><td><select name="product_id[]" class="form-select" required><option value="">Select product</option>@foreach($products as $product)<option value="{{ $product->id }}" @selected(old('product_id.0', $selectedProductId) == $product->id)>{{ $product->name }}</option>@endforeach</select></td><td><select name="uom_id[]" class="form-select"><option value="">Stock unit</option>@foreach($units as $unit)<option value="{{ $unit->id }}">{{ $unit->name }}</option>@endforeach</select></td><td><input name="ordered_qty[]" value="{{ old('ordered_qty.0', $suggestedQuantity) }}" type="number" min="0.000001" step="0.000001" class="form-control" required></td><td><input name="unit_price[]" value="{{ old('unit_price.0', $suggestedPrice) }}" type="number" min="0" step="0.000001" class="form-control" required></td><td><input name="discount_amount[]" type="number" min="0" step="0.000001" value="0" class="form-control"></td><td><button type="button" class="btn btn-outline-danger remove-line">Remove</button></td></tr></tbody></table></div><button type="button" id="add-line" class="btn btn-light">Add line</button> <button class="btn btn-primary">Submit order</button></form></div></div></div></div>
<script>document.getElementById('add-line').addEventListener('click',function(){const row=document.querySelector('#so-lines tbody tr').cloneNode(true);row.querySelectorAll('input').forEach(i=>i.value=i.name==='discount_amount[]'?'0':'');row.querySelectorAll('select').forEach(s=>s.selectedIndex=0);document.querySelector('#so-lines tbody').appendChild(row);});document.addEventListener('click',function(e){if(e.target.classList.contains('remove-line')&&document.querySelectorAll('#so-lines tbody tr').length>1)e.target.closest('tr').remove();});</script>
<script>document.querySelector('form[action="{{ route('fulfillment.orders.store') }}"]').addEventListener('submit',function(){const input=document.createElement('input');input.type='hidden';input.name='store_id';input.value=document.getElementById('order-store').value;this.appendChild(input);});</script>
@endsection
