@extends('admin.admin_master')
@section('admin')
<div class="page-content"><div class="container-fluid"><div class="page-title-box"><h4>Integration API Tokens</h4><p class="text-muted">Create narrowly scoped tokens for ERP integrations. Plain tokens are shown only once.</p></div>
@if(session('plain_token'))<div class="alert alert-warning"><strong>Copy this token now:</strong><input class="form-control mt-2" value="{{ session('plain_token') }}" readonly onclick="this.select()"></div>@endif
<div class="card mb-3"><div class="card-body"><form method="POST" action="{{ route('erp.security.api-tokens.store') }}" class="row g-2">@csrf<div class="col-md-3"><input name="name" class="form-control" placeholder="Token name" required></div>
@foreach(['accounting:read'=>'Accounting read','accounting:write'=>'Accounting write','inventory:read'=>'Inventory read','inventory:write'=>'Inventory write','warehouse:read'=>'Warehouse read','warehouse:write'=>'Warehouse write','manufacturing:read'=>'Manufacturing read','manufacturing:write'=>'Manufacturing write','service:read'=>'Service read','service:write'=>'Service write','sales:read'=>'Sales read','sales:write'=>'Sales write','purchasing:read'=>'Purchasing read','purchasing:write'=>'Purchasing write','integration:read'=>'Integration read','integration:write'=>'Integration write'] as $ability => $label)<div class="col-md-2 form-check mt-2"><input name="abilities[]" value="{{ $ability }}" type="checkbox" class="form-check-input" @checked($ability === 'accounting:read')> {{ $label }}</div>@endforeach
<div class="col-md-2"><button class="btn btn-primary">Create token</button></div></form></div></div>
<div class="card"><div class="card-body table-responsive"><table class="table table-bordered"><thead><tr><th>Name</th><th>Abilities</th><th>Last used</th><th>Created</th><th></th></tr></thead><tbody>@forelse($tokens as $token)<tr><td>{{ $token->name }}</td><td>{{ is_array($token->abilities) ? implode(', ', $token->abilities) : $token->abilities }}</td><td>{{ $token->last_used_at ?? 'Never' }}</td><td>{{ $token->created_at }}</td><td><form method="POST" action="{{ route('erp.security.api-tokens.destroy', $token->id) }}">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger">Revoke</button></form></td></tr>@empty<tr><td colspan="5" class="text-center">No integration tokens.</td></tr>@endforelse</tbody></table></div></div></div></div>
@endsection
