@extends('admin.admin_master')
@section('admin')
<div class="page-content"><div class="container-fluid">
<div class="page-title-box"><h4>Cash Flow Statement</h4><p class="text-muted">Posted journal cash movements classified from configured cash and bank accounts.</p></div>
@if($cashAccounts->isEmpty())<div class="alert alert-warning">Configure a cash, bank, or cash-bank account mapping before using this report.</div>@endif
<div class="card mb-3"><div class="card-body"><form method="GET" class="row g-2"><div class="col-md-5"><label class="form-label">From</label><input type="date" name="from" value="{{ $from }}" class="form-control"></div><div class="col-md-5"><label class="form-label">To</label><input type="date" name="to" value="{{ $to }}" class="form-control"></div><div class="col-md-2 d-flex align-items-end"><button class="btn btn-primary w-100">Refresh</button></div></form></div></div>
<div class="row g-3 mb-3"><div class="col-md-2"><div class="card"><div class="card-body"><small>Opening cash</small><h5>{{ number_format($summary['opening_cash'], 2) }}</h5></div></div></div><div class="col-md-2"><div class="card"><div class="card-body"><small>Operating</small><h5>{{ number_format($summary['operating'], 2) }}</h5></div></div></div><div class="col-md-2"><div class="card"><div class="card-body"><small>Investing</small><h5>{{ number_format($summary['investing'], 2) }}</h5></div></div></div><div class="col-md-2"><div class="card"><div class="card-body"><small>Financing</small><h5>{{ number_format($summary['financing'], 2) }}</h5></div></div></div><div class="col-md-2"><div class="card"><div class="card-body"><small>Net change</small><h5>{{ number_format($summary['net_change'], 2) }}</h5></div></div></div><div class="col-md-2"><div class="card"><div class="card-body"><small>Closing cash</small><h5>{{ number_format($summary['closing_cash'], 2) }}</h5></div></div></div></div>
<div class="card"><div class="card-body"><div class="table-responsive"><table class="table table-bordered"><thead><tr><th>Date</th><th>Entry</th><th>Description</th><th>Classification</th><th>Counterpart accounts</th><th class="text-end">Cash change</th></tr></thead><tbody>@forelse($rows as $row)<tr><td>{{ $row['date'] }}</td><td>{{ $row['entry_no'] }}</td><td>{{ $row['description'] ?: '—' }}</td><td>{{ ucfirst($row['classification']) }}</td><td>{{ implode(', ', $row['counterpart_accounts']) ?: '—' }}</td><td class="text-end">{{ number_format($row['cash_change'], 2) }}</td></tr>@empty<tr><td colspan="6" class="text-center">No posted cash movement found for this period.</td></tr>@endforelse</tbody></table></div></div></div>
</div></div>
@endsection
