@extends('admin.admin_master')
@section('admin')
<div class="page-content"><div class="container-fluid"><div class="page-title-box"><h4>Data Retention & Legal Holds</h4><p class="text-muted">Configure retention intent and protect records before any future archive or purge job runs.</p></div>
<div class="card mb-3"><div class="card-body"><h5>Retention policy</h5><form method="POST" action="{{ route('erp.security.retention.policies.store') }}">@csrf<div class="row g-2"><div class="col-md-3"><input name="name" class="form-control" placeholder="Policy name" required></div><div class="col-md-3"><select name="record_type" class="form-select" required><option value="">Record type</option><option value="audit_logs">Audit logs</option><option value="document_revisions">Document revisions</option></select></div><div class="col-md-2"><input name="retention_days" type="number" min="1" class="form-control" placeholder="Days" required></div><div class="col-md-2 form-check mt-2"><input name="archive_enabled" value="1" type="checkbox" class="form-check-input" checked> Archive enabled</div><div class="col-md-2"><button class="btn btn-primary">Save policy</button></div></div></form></div></div>
<div class="card mb-3"><div class="card-body"><h5>Eligibility preview</h5><form method="POST" action="{{ route('erp.security.retention.preview') }}" class="row g-2"><div class="col-md-5"><select name="policy_id" class="form-select" required><option value="">Select policy</option>@foreach($policies as $policy)<option value="{{ $policy->id }}">{{ $policy->name }} — {{ $policy->retention_days }} days</option>@endforeach</select></div><div class="col-md-3"><button class="btn btn-outline-primary">Preview eligible records</button></div></form></div></div>
<div class="card mb-3"><div class="card-body"><h5>Place legal hold</h5><form method="POST" action="{{ route('erp.security.retention.holds.store') }}">@csrf<div class="row g-2"><div class="col-md-3"><select name="record_type" class="form-select" required><option value="audit_logs">Audit log</option><option value="document_revisions">Document revision</option></select></div><div class="col-md-2"><input name="record_id" type="number" min="1" class="form-control" placeholder="Record ID" required></div><div class="col-md-5"><input name="reason" class="form-control" placeholder="Legal hold reason" required></div><div class="col-md-2"><button class="btn btn-warning">Place hold</button></div></div></form></div></div>
<div class="card"><div class="card-body"><h5>Active legal holds</h5><div class="table-responsive"><table class="table table-bordered"><thead><tr><th>Type</th><th>Record</th><th>Reason</th><th>Placed by</th><th>Date</th><th>Release</th></tr></thead><tbody>@forelse($holds as $hold)<tr><td>{{ $hold->record_type }}</td><td>#{{ $hold->record_id }}</td><td>{{ $hold->reason }}</td><td>{{ $hold->placer->name ?? 'System' }}</td><td>{{ optional($hold->created_at)->format('Y-m-d H:i') }}</td><td><form method="POST" action="{{ route('erp.security.retention.holds.release', $hold->id) }}" class="d-flex gap-1">@csrf<input name="release_reason" class="form-control form-control-sm" placeholder="Release reason" required maxlength="500"><button class="btn btn-sm btn-outline-danger">Release</button></form></td></tr>@empty<tr><td colspan="6" class="text-center">No active legal holds.</td></tr>@endforelse</tbody></table>{{ $holds->links() }}</div></div></div></div></div>
<div class="card mt-3"><div class="card-body"><div class="d-flex justify-content-between align-items-center"><h5 class="mb-0">Archive snapshots</h5><a class="btn btn-sm btn-outline-secondary" href="{{ route('erp.security.retention.archives.export') }}">Export CSV</a></div><div class="table-responsive mt-2"><table class="table table-bordered"><thead><tr><th>ID</th><th>Type</th><th>Record</th><th>Archived</th><th>Payload hash</th></tr></thead><tbody>@forelse($archives as $archive)<tr><td>{{ $archive->id }}</td><td>{{ $archive->record_type }}</td><td>#{{ $archive->record_id }}</td><td>{{ optional($archive->archived_at)->format('Y-m-d H:i') }}</td><td><code>{{ $archive->payload_hash }}</code></td></tr>@empty<tr><td colspan="5" class="text-center">No archive snapshots.</td></tr>@endforelse</tbody></table>{{ $archives->links('pagination::bootstrap-4', ['pageName' => 'archives_page']) }}</div></div></div></div>
@endsection
