@extends('admin.admin_master')
@section('admin')
<div class="page-content"><div class="container-fluid">
<div class="page-title-box"><h4>Financial Statements</h4><p class="text-muted">Posted-journal Profit &amp; Loss for the period and Balance Sheet as of the end date.</p></div>
<div class="card mb-3"><div class="card-body"><form method="GET" class="row g-2"><div class="col-md-4"><label class="form-label">From</label><input type="date" name="from" value="{{ $from }}" class="form-control"></div><div class="col-md-4"><label class="form-label">To / As of</label><input type="date" name="to" value="{{ $to }}" class="form-control"></div><div class="col-md-2 d-flex align-items-end"><button class="btn btn-primary w-100">Refresh</button></div></form></div></div>
<div class="row g-3"><div class="col-lg-6"><div class="card h-100"><div class="card-body"><h5>Profit &amp; Loss</h5><table class="table table-sm"><thead><tr><th>Account</th><th>Type</th><th class="text-end">Balance</th></tr></thead><tbody>@forelse($profitAndLoss as $row)<tr><td>{{ $row['code'] }} — {{ $row['name'] }}</td><td>{{ ucfirst($row['account_type']) }}</td><td class="text-end">{{ number_format($row['period_balance'], 2) }}</td></tr>@empty<tr><td colspan="3">No income or expense activity.</td></tr>@endforelse</tbody><tfoot><tr><th colspan="2">Net income</th><th class="text-end">{{ number_format($summary['net_income'], 2) }}</th></tr></tfoot></table></div></div></div>
<div class="col-lg-6"><div class="card h-100"><div class="card-body"><h5>Balance Sheet</h5><table class="table table-sm"><thead><tr><th>Account</th><th>Type</th><th class="text-end">Balance</th></tr></thead><tbody>@forelse($balanceSheet as $row)<tr><td>{{ $row['code'] }} — {{ $row['name'] }}</td><td>{{ ucfirst($row['account_type']) }}</td><td class="text-end">{{ number_format($row['as_of_balance'], 2) }}</td></tr>@empty<tr><td colspan="3">No balance-sheet activity.</td></tr>@endforelse</tbody><tfoot><tr><th colspan="2">Assets</th><th class="text-end">{{ number_format($summary['assets'], 2) }}</th></tr><tr><th colspan="2">Liabilities + equity + net income</th><th class="text-end">{{ number_format($summary['equity_and_net_income'] + $summary['liabilities'], 2) }}</th></tr><tr><th colspan="2">Difference</th><th class="text-end">{{ number_format($summary['balance_difference'], 2) }}</th></tr></tfoot></table></div></div></div></div>
</div></div>
@endsection
