@extends('admin.admin_master')
@section('admin')
<div class="page-content"><div class="container-fluid">
<div class="page-title-box"><h4>Attendance</h4><p class="text-muted">Daily employee attendance and worked-minute records.</p></div>
@if(session('message'))<div class="alert alert-{{ session('alert-type', 'info') }}">{{ session('message') }}</div>@endif
<div class="card mb-3"><div class="card-body"><form method="POST" action="{{ route('erp.hr.attendance.store') }}" class="row g-2">@csrf<div class="col-md-3"><select name="employee_id" class="form-select" required><option value="">Employee</option>@foreach($employees as $employee)<option value="{{ $employee->id }}">{{ $employee->employee_no }} — {{ $employee->first_name }} {{ $employee->last_name }}</option>@endforeach</select></div><div class="col-md-2"><input name="attendance_date" type="date" value="{{ now()->toDateString() }}" class="form-control" required></div><div class="col-md-2"><select name="status" class="form-select"><option value="present">Present</option><option value="absent">Absent</option><option value="leave">Leave</option><option value="holiday">Holiday</option></select></div><div class="col-md-2"><input name="check_in" type="time" class="form-control"></div><div class="col-md-2"><input name="check_out" type="time" class="form-control"></div><div class="col-md-1"><button class="btn btn-primary w-100">Save</button></div></form></div></div>
<div class="card"><div class="card-body"><form method="GET" class="row g-2 mb-3"><div class="col-md-4"><input name="from" type="date" value="{{ $from }}" class="form-control"></div><div class="col-md-4"><input name="to" type="date" value="{{ $to }}" class="form-control"></div><div class="col-md-2"><button class="btn btn-outline-secondary w-100">Filter</button></div></form><table class="table table-bordered"><thead><tr><th>Date</th><th>Employee</th><th>Status</th><th>Check in</th><th>Check out</th><th>Worked minutes</th><th>Note</th></tr></thead><tbody>@forelse($attendance as $row)<tr><td>{{ $row->attendance_date->toDateString() }}</td><td>{{ $row->employee?->employee_no }} — {{ $row->employee?->first_name }}</td><td>{{ ucfirst($row->status) }}</td><td>{{ $row->check_in ?: '—' }}</td><td>{{ $row->check_out ?: '—' }}</td><td>{{ $row->worked_minutes }}</td><td>{{ $row->note ?: '—' }}</td></tr>@empty<tr><td colspan="7" class="text-center">No attendance records found.</td></tr>@endforelse</tbody></table>{{ $attendance->links() }}</div></div>
</div></div>
@endsection
