@extends('admin.admin_master')
@section('admin')
<div class="page-content"><div class="container-fluid">
<div class="page-title-box"><h4>Employees</h4><p class="text-muted">Company workforce master for HR and future payroll processing.</p></div>
@if(session('message'))<div class="alert alert-{{ session('alert-type', 'info') }}">{{ session('message') }}</div>@endif
<div class="card mb-3"><div class="card-body"><h5>Add employee</h5><form method="POST" action="{{ route('erp.hr.employees.store') }}" class="row g-2">@csrf
<div class="col-md-2"><input name="employee_no" class="form-control" placeholder="Employee no." required></div><div class="col-md-2"><input name="first_name" class="form-control" placeholder="First name" required></div><div class="col-md-2"><input name="last_name" class="form-control" placeholder="Last name"></div><div class="col-md-3"><input name="job_title" class="form-control" placeholder="Job title"></div><div class="col-md-3"><input name="email" type="email" class="form-control" placeholder="Email"></div>
<div class="col-md-2"><select name="branch_id" class="form-select"><option value="">Branch</option>@foreach($branches as $branch)<option value="{{ $branch->id }}">{{ $branch->name }}</option>@endforeach</select></div><div class="col-md-2"><select name="department_id" class="form-select"><option value="">Department</option>@foreach($departments as $department)<option value="{{ $department->id }}">{{ $department->name }}</option>@endforeach</select></div><div class="col-md-2"><select name="employment_type" class="form-select"><option value="full_time">Full time</option><option value="part_time">Part time</option><option value="contract">Contract</option><option value="temporary">Temporary</option></select></div><div class="col-md-2"><select name="pay_frequency" class="form-select"><option value="monthly">Monthly</option><option value="biweekly">Biweekly</option><option value="weekly">Weekly</option></select></div><div class="col-md-2"><input name="basic_salary" type="number" min="0" step="0.000001" class="form-control" placeholder="Basic salary" required></div><div class="col-md-2"><input name="currency_code" maxlength="3" class="form-control" placeholder="Currency"></div><div class="col-md-2"><button class="btn btn-primary w-100">Create</button></div>
</form></div></div>
<div class="card"><div class="card-body"><div class="table-responsive"><table class="table table-bordered"><thead><tr><th>Employee</th><th>Job title</th><th>Organization</th><th>Employment</th><th>Salary</th><th>Status</th><th>Benefits / Action</th></tr></thead><tbody>@forelse($employees as $employee)<tr><td>{{ $employee->employee_no }} — {{ $employee->first_name }} {{ $employee->last_name }}</td><td>{{ $employee->job_title ?: '—' }}</td><td>{{ $employee->branch?->name ?: '—' }} / {{ $employee->department?->name ?: '—' }}</td><td>{{ ucfirst(str_replace('_', ' ', $employee->employment_type)) }} / {{ ucfirst($employee->pay_frequency) }}</td><td>{{ $employee->currency_code ?: '' }} {{ number_format((float) $employee->basic_salary, 2) }}</td><td>{{ ucfirst($employee->status) }}</td><td><div class="small mb-1">@forelse($employee->benefits->where('is_active', true) as $benefit)<span class="badge bg-light text-dark">{{ $benefit->code }}: {{ ucfirst($benefit->benefit_type) }} {{ $benefit->calculation === 'percentage' ? number_format((float) $benefit->value, 2).'%' : number_format((float) $benefit->value, 2) }}</span> <form class="d-inline" method="POST" action="{{ route('erp.hr.employees.benefits.deactivate', [$employee->id, $benefit->id]) }}">@csrf<button class="btn btn-link btn-sm p-0 text-danger">×</button></form>@empty — @endforelse</div><form method="POST" action="{{ route('erp.hr.employees.benefits.store', $employee->id) }}" class="row g-1">@csrf<div class="col-3"><input name="code" class="form-control form-control-sm" placeholder="Code" required></div><div class="col-4"><input name="name" class="form-control form-control-sm" placeholder="Name" required></div><div class="col-2"><select name="benefit_type" class="form-select form-select-sm"><option value="earning">Earn</option><option value="deduction">Deduct</option></select></div><div class="col-2"><input name="value" type="number" min="0" step="0.000001" class="form-control form-control-sm" placeholder="Value" required></div><div class="col-1"><button class="btn btn-sm btn-outline-primary">+</button></div><input type="hidden" name="calculation" value="fixed"></form>@if($employee->status !== 'terminated')<form class="mt-1" method="POST" action="{{ route('erp.hr.employees.terminate', $employee->id) }}">@csrf<button class="btn btn-sm btn-outline-danger">Terminate</button></form>@endif</td></tr>@empty<tr><td colspan="7" class="text-center">No employees found.</td></tr>@endforelse</tbody></table></div>{{ $employees->links() }}</div></div>
</div></div>
@endsection
