@extends('admin.admin_master')
@section('admin')
<div class="page-content"><div class="container-fluid">
<div class="page-title-box"><h4>Leave Management</h4><p class="text-muted">Calendar-day leave requests with company entitlements and approval controls.</p></div>
@if($errors->has('leave'))<div class="alert alert-danger">{{ $errors->first('leave') }}</div>@endif @if(session('message'))<div class="alert alert-{{ session('alert-type', 'info') }}">{{ session('message') }}</div>@endif
<div class="row g-3"><div class="col-lg-5"><div class="card mb-3"><div class="card-body"><h5>Leave type</h5><form method="POST" action="{{ route('erp.hr.leave-types.store') }}" class="row g-2">@csrf<div class="col-4"><input name="code" class="form-control" placeholder="Code" required></div><div class="col-8"><input name="name" class="form-control" placeholder="Name" required></div><div class="col-6"><input name="annual_entitlement" type="number" min="0" step="0.001" class="form-control" placeholder="Annual days" required></div><div class="col-6"><button class="btn btn-primary w-100">Create type</button></div></form></div></div><div class="card"><div class="card-body"><h5>Request leave</h5><form method="POST" action="{{ route('erp.hr.leave-requests.store') }}" class="row g-2">@csrf<div class="col-12"><select name="employee_id" class="form-select" required><option value="">Employee</option>@foreach($employees as $employee)<option value="{{ $employee->id }}">{{ $employee->employee_no }} — {{ $employee->first_name }} {{ $employee->last_name }}</option>@endforeach</select></div><div class="col-12"><select name="leave_type_id" class="form-select" required><option value="">Leave type</option>@foreach($types as $type)<option value="{{ $type->id }}">{{ $type->code }} — {{ $type->name }} ({{ $type->annual_entitlement }} days)</option>@endforeach</select></div><div class="col-6"><input name="starts_on" type="date" class="form-control" required></div><div class="col-6"><input name="ends_on" type="date" class="form-control" required></div><div class="col-12"><textarea name="reason" class="form-control" placeholder="Reason"></textarea></div><div class="col-12"><button class="btn btn-primary w-100">Submit request</button></div></form></div></div></div>
<div class="col-lg-7"><div class="card"><div class="card-body"><table class="table table-bordered"><thead><tr><th>Employee</th><th>Type</th><th>Dates</th><th>Days</th><th>Status</th><th>Action</th></tr></thead><tbody>@forelse($requests as $request)<tr><td>{{ $request->employee?->employee_no }} — {{ $request->employee?->first_name }}</td><td>{{ $request->leaveType?->name }}</td><td>{{ $request->starts_on->toDateString() }} — {{ $request->ends_on->toDateString() }}</td><td>{{ $request->days }}</td><td>{{ ucfirst($request->status) }}</td><td>@if($request->status === 'pending')<form method="POST" action="{{ route('erp.hr.leave-requests.approve', $request->id) }}" class="d-inline">@csrf<button class="btn btn-sm btn-outline-success">Approve</button></form><form method="POST" action="{{ route('erp.hr.leave-requests.reject', $request->id) }}" class="d-inline">@csrf<input type="hidden" name="decision_reason" value="Rejected by reviewer"><button class="btn btn-sm btn-outline-danger">Reject</button></form>@else — @endif</td></tr>@empty<tr><td colspan="6" class="text-center">No leave requests found.</td></tr>@endforelse</tbody></table>{{ $requests->links() }}</div></div></div></div>
</div></div>
@endsection
