@extends('admin.admin_master')
@section('admin')
<div class="page-content"><div class="container-fluid">
<div class="page-title-box"><h4>Payroll Runs</h4><p class="text-muted">Generate basic-salary payslips for active employees matching a pay frequency.</p></div>
@if($errors->has('pay_run') || $errors->has('period_from'))<div class="alert alert-danger">{{ $errors->first('pay_run') ?: $errors->first('period_from') }}</div>@endif
@if(session('message'))<div class="alert alert-{{ session('alert-type', 'info') }}">{{ session('message') }}</div>@endif
<div class="card mb-3"><div class="card-body"><form method="POST" action="{{ route('erp.hr.pay-runs.store') }}" class="row g-2">@csrf
<div class="col-md-2"><input name="run_no" class="form-control" placeholder="Run no." required></div><div class="col-md-2"><select name="frequency" class="form-select"><option value="monthly">Monthly</option><option value="biweekly">Biweekly</option><option value="weekly">Weekly</option></select></div><div class="col-md-2"><input name="period_from" type="date" class="form-control" required></div><div class="col-md-2"><input name="period_to" type="date" class="form-control" required></div><div class="col-md-2"><input name="pay_date" type="date" class="form-control" placeholder="Pay date"></div><div class="col-md-2"><button class="btn btn-primary w-100">Generate</button></div>
<div class="mt-2"><label class="form-label mb-0">Attendance policy</label><select name="attendance_policy" class="form-select form-select-sm" style="max-width:240px"><option value="ignore">Ignore attendance</option><option value="unpaid_absence">Deduct unpaid absence</option></select></div></form></div></div>
<div class="card mb-3"><div class="card-body"><h5>Payroll rules</h5><form method="POST" action="{{ route('erp.hr.payroll-rules.store') }}" class="row g-2">@csrf<div class="col-md-2"><input name="code" class="form-control" placeholder="Code" required></div><div class="col-md-3"><input name="name" class="form-control" placeholder="Rule name" required></div><div class="col-md-2"><select name="rule_type" class="form-select"><option value="earning">Earning</option><option value="deduction">Deduction</option></select></div><div class="col-md-2"><select name="calculation" class="form-select"><option value="percentage">Percentage</option><option value="fixed">Fixed</option></select></div><div class="col-md-2"><input name="value" type="number" min="0" step="0.000001" class="form-control" placeholder="Value" required></div><div class="col-md-1"><button class="btn btn-primary w-100">Add</button></div></form><div class="mt-2">@forelse($rules as $rule)<span class="badge bg-{{ $rule->is_active ? 'success' : 'secondary' }} me-1">{{ $rule->code }}: {{ $rule->rule_type }} {{ $rule->calculation }} {{ $rule->value }}@if($rule->is_active)<form method="POST" action="{{ route('erp.hr.payroll-rules.deactivate', $rule->id) }}" class="d-inline ms-1">@csrf<button class="btn btn-link btn-sm p-0 text-white">×</button></form>@endif</span>@empty<small class="text-muted">No payroll rules configured.</small>@endforelse</div></div></div>
<div class="card"><div class="card-body"><div class="table-responsive"><table class="table table-bordered"><thead><tr><th>Run</th><th>Period</th><th>Frequency</th><th>Payslips</th><th>Gross</th><th>Deductions</th><th>Net</th><th>Status</th><th>Action</th></tr></thead><tbody>@forelse($payRuns as $run)<tr><td>{{ $run->run_no }}</td><td>{{ $run->period_from->toDateString() }} — {{ $run->period_to->toDateString() }}</td><td>{{ ucfirst($run->frequency) }}</td><td>{{ $run->payslips_count }}</td><td>{{ number_format((float) $run->gross_total, 2) }}</td><td>{{ number_format((float) $run->deduction_total, 2) }}</td><td>{{ number_format((float) $run->net_total, 2) }}</td><td>{{ ucfirst($run->status) }}@if($run->paid_at)<br><small>{{ $run->paid_at->toDateString() }}</small>@endif</td><td>@if($run->status === 'draft')<form method="POST" action="{{ route('erp.hr.pay-runs.approve', $run->id) }}">@csrf<button class="btn btn-sm btn-outline-success">Approve</button></form>@elseif($run->status === 'approved')<form method="POST" action="{{ route('erp.hr.pay-runs.pay', $run->id) }}" class="d-flex gap-1"><input type="hidden" name="paid_at" value="{{ now()->toDateString() }}"><input class="form-control form-control-sm" name="payment_reference" placeholder="Payment reference"><button class="btn btn-sm btn-outline-primary">Pay</button></form>@else — @endif</td></tr>@empty<tr><td colspan="9" class="text-center">No payroll runs found.</td></tr>@endforelse</tbody></table></div>{{ $payRuns->links() }}</div></div>
</div></div>
@endsection
