@extends('admin.admin_master')
@section('admin')
<div class="page-content"><div class="container-fluid">
    <div class="page-title-box"><h4>Organization and Locations</h4><p class="text-muted mb-0">Configure companies, branches, warehouses, and storage locations.</p></div>
    @include('admin.erp.company_maintenance')
    @include('admin.erp.department_maintenance')
    @include('admin.erp.branch_maintenance')
    @include('admin.erp.store_maintenance')
    @include('admin.erp.warehouse_maintenance')
    @include('admin.erp.location_maintenance')
    <div class="row g-3">
        <div class="col-xl-6"><div class="card"><div class="card-body"><h5>Create department</h5><form method="POST" action="{{ route('erp.organization.department') }}">@csrf<div class="row g-2"><div class="col-12"><select name="company_id" class="form-select" required><option value="">Select company</option>@foreach($companies as $company)<option value="{{ $company->id }}">{{ $company->name }}</option>@endforeach</select></div><div class="col-md-8"><input name="name" placeholder="Department name" class="form-control" required></div><div class="col-md-4"><input name="code" placeholder="Code" class="form-control" required></div></div><button class="btn btn-primary mt-3">Create department</button></form></div></div></div>
        <div class="col-xl-6"><div class="card"><div class="card-body"><h5>Create store</h5><form method="POST" action="{{ route('erp.organization.store') }}">@csrf<div class="row g-2"><div class="col-12"><select name="branch_id" class="form-select" required><option value="">Select branch</option>@foreach($companies as $company)@foreach($company->branches as $branch)<option value="{{ $branch->id }}">{{ $company->name }} / {{ $branch->name }}</option>@endforeach @endforeach</select></div><div class="col-12"><select name="warehouse_id" class="form-select"><option value="">Fulfillment warehouse (optional)</option>@foreach($companies as $company)@foreach($company->branches as $branch)@foreach($branch->warehouses as $warehouse)<option value="{{ $warehouse->id }}">{{ $company->name }} / {{ $branch->name }} / {{ $warehouse->name }}</option>@endforeach @endforeach @endforeach</select></div><div class="col-md-8"><input name="name" placeholder="Store name" class="form-control" required></div><div class="col-md-4"><input name="code" placeholder="Code" class="form-control" required></div><div class="col-md-4"><input name="currency_code" value="USD" maxlength="3" placeholder="Currency" class="form-control"></div><div class="col-md-4"><select name="default_tax_mode" class="form-select"><option value="">Default tax mode</option><option value="exclusive">Exclusive</option><option value="inclusive">Inclusive</option></select></div><div class="col-md-4 form-check mt-2"><input name="allow_negative_stock" value="1" type="checkbox" class="form-check-input" id="store-negative"><label class="form-check-label" for="store-negative">Allow negative stock</label></div><div class="col-12"><textarea name="address" placeholder="Address" class="form-control"></textarea></div></div><button class="btn btn-primary mt-3">Create store</button></form></div></div></div>
        <div class="col-xl-6"><div class="card"><div class="card-body"><h5>Create company</h5><form method="POST" action="{{ route('erp.organization.company') }}">@csrf<div class="row g-2"><div class="col-md-8"><input name="name" placeholder="Company name" class="form-control" required></div><div class="col-md-4"><input name="code" placeholder="Code" class="form-control" required></div><div class="col-md-4"><input name="base_currency" value="USD" maxlength="3" placeholder="Currency" class="form-control" required></div><div class="col-md-8"><input name="tax_number" placeholder="Tax number" class="form-control"></div><div class="col-12"><input name="email" type="email" placeholder="Email" class="form-control"></div><div class="col-12"><textarea name="address" placeholder="Address" class="form-control"></textarea></div></div><button class="btn btn-primary mt-3">Create company</button></form></div></div></div>
        <div class="col-xl-6"><div class="card"><div class="card-body"><h5>Create branch</h5><form method="POST" action="{{ route('erp.organization.branch') }}">@csrf<div class="row g-2"><div class="col-12"><select name="company_id" class="form-select" required><option value="">Select company</option>@foreach($companies as $company)<option value="{{ $company->id }}">{{ $company->name }} ({{ $company->code }})</option>@endforeach</select></div><div class="col-md-8"><input name="name" placeholder="Branch name" class="form-control" required></div><div class="col-md-4"><input name="code" placeholder="Code" class="form-control" required></div><div class="col-12"><textarea name="address" placeholder="Address" class="form-control"></textarea></div></div><button class="btn btn-primary mt-3">Create branch</button></form></div></div></div>
        <div class="col-xl-6"><div class="card"><div class="card-body"><h5>Create warehouse</h5><form method="POST" action="{{ route('erp.organization.warehouse') }}">@csrf<div class="row g-2"><div class="col-12"><select name="branch_id" class="form-select" required><option value="">Select branch</option>@foreach($companies as $company)@foreach($company->branches as $branch)<option value="{{ $branch->id }}">{{ $company->name }} / {{ $branch->name }}</option>@endforeach @endforeach</select></div><div class="col-md-8"><input name="name" placeholder="Warehouse name" class="form-control" required></div><div class="col-md-4"><input name="code" placeholder="Code" class="form-control" required></div><div class="col-md-6"><select name="warehouse_type" class="form-select"><option value="standard">Standard</option><option value="distribution">Distribution</option><option value="retail">Retail</option><option value="manufacturing">Manufacturing</option><option value="quarantine">Quarantine</option><option value="transit">Transit</option></select></div><div class="col-md-6"><input name="manager_name" placeholder="Manager" class="form-control"></div></div><button class="btn btn-primary mt-3">Create warehouse</button></form></div></div></div>
        <div class="col-xl-6"><div class="card"><div class="card-body"><h5>Create storage location</h5><form method="POST" action="{{ route('erp.organization.location') }}">@csrf<div class="row g-2"><div class="col-12"><select name="warehouse_id" class="form-select" required><option value="">Select warehouse</option>@foreach($companies as $company)@foreach($company->branches as $branch)@foreach($branch->warehouses as $warehouse)<option value="{{ $warehouse->id }}">{{ $company->name }} / {{ $branch->name }} / {{ $warehouse->name }}</option>@endforeach @endforeach @endforeach</select></div><div class="col-md-6"><input name="name" placeholder="Location name" class="form-control" required></div><div class="col-md-6"><input name="code" placeholder="Location code" class="form-control" required></div><div class="col-md-6"><select name="type" class="form-select"><option value="zone">Zone</option><option value="rack">Rack</option><option value="shelf">Shelf</option><option value="bin" selected>Bin</option></select></div><div class="col-md-6"><select name="parent_id" class="form-select"><option value="">Parent location (optional)</option>@foreach($companies as $company)@foreach($company->branches as $branch)@foreach($branch->warehouses as $warehouse)@foreach($warehouse->locations as $location)<option value="{{ $location->id }}">{{ $company->name }} / {{ $warehouse->name }} / {{ $location->code }} ({{ $location->type }})</option>@endforeach @endforeach @endforeach @endforeach</select></div><div class="col-md-4"><input name="capacity" type="number" step="0.000001" min="0" placeholder="Quantity capacity" class="form-control"></div><div class="col-md-4"><input name="capacity_weight_kg" type="number" step="0.000001" min="0" placeholder="Weight capacity (kg)" class="form-control"></div><div class="col-md-4"><input name="capacity_volume_m3" type="number" step="0.000001" min="0" placeholder="Volume capacity (m³)" class="form-control"></div></div><button class="btn btn-primary mt-3">Create location</button></form></div></div></div>
    </div>
    <div class="card"><div class="card-body"><h5>Configure location zoning</h5><p class="text-muted">Allow or deny a product or category. Rules inherit through parent locations.</p><form method="POST" action="{{ route('erp.organization.location-rule') }}" class="row g-2">@csrf<div class="col-md-4"><select name="location_id" class="form-select" required><option value="">Select location</option>@foreach($companies as $company)@foreach($company->branches as $branch)@foreach($branch->warehouses as $warehouse)@foreach($warehouse->locations as $location)<option value="{{ $location->id }}">{{ $company->name }} / {{ $warehouse->name }} / {{ $location->code }}</option>@endforeach @endforeach @endforeach @endforeach</select></div><div class="col-md-3"><select name="product_id" class="form-select"><option value="">Product (optional)</option>@foreach($products as $product)<option value="{{ $product->id }}">{{ $product->name }}{{ $product->sku ? ' — '.$product->sku : '' }}</option>@endforeach</select></div><div class="col-md-3"><select name="category_id" class="form-select"><option value="">Category (optional)</option>@foreach($categories as $category)<option value="{{ $category->id }}">{{ $category->name }}</option>@endforeach</select></div><div class="col-md-2"><select name="rule_type" class="form-select" required><option value="allow">Allow</option><option value="deny">Deny</option></select></div><div class="col-12"><button class="btn btn-primary">Save zoning rule</button></div></form><div class="table-responsive mt-3"><table class="table table-sm"><thead><tr><th>Location</th><th>Target</th><th>Rule</th><th>Status</th><th></th></tr></thead><tbody>@forelse($rules as $rule)<tr><td>{{ $rule->location?->code }}</td><td>{{ $rule->product?->name ?: ($rule->category?->name ?: '—') }}</td><td>{{ ucfirst($rule->rule_type) }}</td><td>{{ $rule->is_active ? 'Active' : 'Inactive' }}</td><td>@if($rule->is_active)<form method="POST" action="{{ route('erp.organization.location-rule.deactivate', $rule->id) }}">@csrf<button class="btn btn-sm btn-outline-danger">Deactivate</button></form>@endif</td></tr>@empty<tr><td colspan="5" class="text-muted">No zoning rules configured.</td></tr>@endforelse</tbody></table></div></div></div>
    <div class="card"><div class="card-body"><h5>Configured structure</h5>@forelse($companies as $company)<div class="mb-3"><strong>{{ $company->name }} ({{ $company->code }})</strong><div class="ms-3">Departments: {{ $company->departments->pluck('name')->join(', ') ?: 'None' }}</div>@forelse($company->branches as $branch)<div class="ms-3">Branch: {{ $branch->name }} ({{ $branch->code }}) — Stores: {{ $branch->stores->pluck('name')->join(', ') ?: 'None' }}@forelse($branch->warehouses as $warehouse)<div class="ms-3">Warehouse: {{ $warehouse->name }} ({{ $warehouse->code }}) — {{ $warehouse->locations->count() }} location(s)</div>@empty <div class="ms-3 text-muted">No locations</div>@endforelse</div>@empty <div class="ms-3 text-muted">No warehouses</div>@endforelse</div>@empty <p class="text-muted">No companies configured.</p>@endforelse</div></div>
</div></div>
@endsection
