@extends('admin.admin_master')
@section('admin')
<div class="container-fluid py-3"><h4>Named price lists</h4><p class="text-muted">Reusable quantity-break defaults apply after customer/supplier-specific agreements.</p>
@if(session('message'))<div class="alert alert-success">{{ session('message') }}</div>@endif @if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="row g-3"><div class="col-lg-5"><div class="card"><div class="card-body"><h5>Create list</h5><form method="POST" action="{{ route('erp.pricing.lists.store') }}">@csrf<div class="mb-2"><input name="name" class="form-control" placeholder="Name" required></div><div class="row g-2"><div class="col"><select name="list_type" class="form-control"><option value="sales">Sales</option><option value="purchase">Purchase</option></select></div><div class="col"><input name="currency_code" value="USD" maxlength="3" class="form-control" required></div></div><div class="row g-2 mt-1"><div class="col"><input name="starts_on" type="date" class="form-control"></div><div class="col"><input name="ends_on" type="date" class="form-control"></div></div><button class="btn btn-primary mt-2">Create</button></form></div></div></div>
<div class="col-lg-7"><div class="card"><div class="card-body"><h5>Add item</h5><form method="POST" action="{{ route('erp.pricing.lists.item') }}">@csrf<div class="row g-2"><div class="col"><select name="price_list_id" class="form-control" required><option value="">Price list</option>@foreach($lists as $list)<option value="{{ $list->id }}">{{ $list->name }} ({{ $list->list_type }})</option>@endforeach</select></div><div class="col"><select name="product_id" class="form-control" required><option value="">Product</option>@foreach($products as $product)<option value="{{ $product->id }}">{{ $product->name }} ({{ $product->sku }})</option>@endforeach</select></div><div class="col"><input name="minimum_quantity" type="number" step="0.000001" min="0.000001" value="1" class="form-control" placeholder="Min qty"></div><div class="col"><input name="unit_price" type="number" step="0.000001" min="0" class="form-control" placeholder="Price"></div><div class="col"><input name="discount_percent" type="number" step="0.0001" min="0" max="100" value="0" class="form-control" placeholder="Disc %"></div></div><button class="btn btn-primary mt-2">Add item</button></form></div></div></div></div>
<div class="card mt-3"><div class="card-body"><h5>Lists</h5><div class="table-responsive"><table class="table table-sm"><thead><tr><th>Name</th><th>Type</th><th>Currency</th><th>Items</th><th>Status</th><th></th></tr></thead><tbody>@forelse($lists as $list)<tr><td>{{ $list->name }}</td><td>{{ ucfirst($list->list_type) }}</td><td>{{ $list->currency_code }}</td><td>{{ $list->items_count }}</td><td>{{ $list->is_active ? 'Active' : 'Inactive' }}</td><td>@if($list->is_active)<form method="POST" action="{{ route('erp.pricing.lists.deactivate', $list->id) }}">@csrf<button class="btn btn-sm btn-outline-danger">Deactivate</button></form>@endif</td></tr>@empty<tr><td colspan="6">No named price lists.</td></tr>@endforelse</tbody></table></div>{{ $lists->links() }}</div></div>
<div class="row g-3 mt-1"><div class="col-lg-6"><div class="card"><div class="card-body"><h5>Assign sales list</h5><form method="POST" action="{{ route('erp.pricing.lists.assign-customer') }}">@csrf<select name="customer_id" class="form-control mb-2" required><option value="">Customer</option>@foreach($customers as $customer)<option value="{{ $customer->id }}">{{ $customer->name }}</option>@endforeach</select><select name="price_list_id" class="form-control mb-2"><option value="">No list</option>@foreach($lists->getCollection()->where('list_type','sales') as $list)<option value="{{ $list->id }}">{{ $list->name }}</option>@endforeach</select><button class="btn btn-outline-primary">Assign</button></form></div></div></div><div class="col-lg-6"><div class="card"><div class="card-body"><h5>Assign purchase list</h5><form method="POST" action="{{ route('erp.pricing.lists.assign-supplier') }}">@csrf<select name="supplier_id" class="form-control mb-2" required><option value="">Supplier</option>@foreach($suppliers as $supplier)<option value="{{ $supplier->id }}">{{ $supplier->name }}</option>@endforeach</select><select name="price_list_id" class="form-control mb-2"><option value="">No list</option>@foreach($lists->getCollection()->where('list_type','purchase') as $list)<option value="{{ $list->id }}">{{ $list->name }}</option>@endforeach</select><button class="btn btn-outline-primary">Assign</button></form></div></div></div></div>
</div>
@endsection
