@extends('admin.admin_master')

@section('admin')
<div class="page-content"><div class="container-fluid">
    <div class="page-title-box"><h4>Production Variance</h4><p class="text-muted">Compare BOM material and routing operation costs with actual consumption and production yield.</p></div>
    <div class="card mb-3"><div class="card-body"><form class="row g-2"><div class="col-md-3"><label>Planned from</label><input type="date" name="from" value="{{ $filters['from'] ?? '' }}" class="form-control"></div><div class="col-md-3"><label>Planned to</label><input type="date" name="to" value="{{ $filters['to'] ?? '' }}" class="form-control"></div><div class="col-md-3"><label>Status</label><select name="status" class="form-select"><option value="">All statuses</option>@foreach(['draft','released','in_progress','paused','completed','closed','cancelled'] as $status)<option value="{{ $status }}" @selected(($filters['status'] ?? '') === $status)>{{ ucfirst(str_replace('_', ' ', $status)) }}</option>@endforeach</select></div><div class="col-md-2 d-flex align-items-end"><button class="btn btn-primary">Filter</button></div></form></div></div>
    <div class="card"><div class="card-body"><div class="table-responsive"><table class="table table-bordered"><thead><tr><th>Order</th><th>Product</th><th>Yield</th><th>Material variance</th><th>Operation variance</th><th>Total variance</th><th>Components</th></tr></thead><tbody>@forelse($rows as $row)<tr><td>{{ $row['order_no'] }}</td><td>{{ data_get($row, 'product.name', '—') }}</td><td>{{ number_format($row['completed_quantity'], 3) }} / {{ number_format($row['planned_quantity'], 3) }}<br><small class="text-muted">Variance {{ number_format($row['yield_variance'], 3) }}</small></td><td>{{ number_format($row['material_cost_variance'], 2) }}</td><td>{{ number_format($row['operation_cost_variance'], 2) }}</td><td class="fw-bold">{{ number_format($row['total_cost_variance'], 2) }}</td><td><details><summary>{{ count($row['components']) }} component(s)</summary>@foreach($row['components'] as $component)<div class="small mt-1">{{ data_get($component, 'product.name', 'Unknown') }}: planned {{ number_format($component['planned_quantity'], 3) }}, actual {{ number_format($component['actual_quantity'], 3) }}, cost variance {{ number_format($component['cost_variance'], 2) }}</div>@endforeach</details></td></tr>@empty<tr><td colspan="7" class="text-center">No production variance records found.</td></tr>@endforelse</tbody></table></div></div></div>
</div></div>
@endsection
