@extends('admin.admin_master')
@section('admin')
<div class="page-content"><div class="container-fluid">
    <div class="page-title-box"><h4>Tax Report</h4><p class="text-muted">Approved sales and purchase tax activity by rate and jurisdiction.</p></div>
    <div class="card mb-3"><div class="card-body"><form method="GET" action="{{ route('erp.accounting.tax-report') }}" class="row g-2"><div class="col-md-3"><label class="form-label">From</label><input type="date" name="from" value="{{ $from }}" class="form-control"></div><div class="col-md-3"><label class="form-label">To</label><input type="date" name="to" value="{{ $to }}" class="form-control"></div><div class="col-md-3"><label class="form-label">Jurisdiction</label><input type="text" name="jurisdiction" value="{{ $jurisdiction }}" maxlength="100" class="form-control" placeholder="All jurisdictions"></div><div class="col-md-2 d-flex align-items-end"><button class="btn btn-primary w-100">Filter</button></div></form></div></div>
    <div class="card"><div class="card-body"><div class="table-responsive"><table class="table table-bordered"><thead><tr><th>Tax rate</th><th>Jurisdiction</th><th>Sales taxable</th><th>Output tax</th><th>Purchase taxable</th><th>Input tax</th><th>Net payable/(credit)</th><th>Documents</th></tr></thead><tbody>
    @forelse($rows as $row)<tr><td>{{ number_format($row['rate'], 2) }}%</td><td>{{ $row['jurisdiction'] ?: 'Unspecified' }}</td><td>{{ number_format($row['sales']['taxable'], 2) }}</td><td>{{ number_format($row['sales']['tax'], 2) }}</td><td>{{ number_format($row['purchases']['taxable'], 2) }}</td><td>{{ number_format($row['purchases']['tax'], 2) }}</td><td class="{{ ($row['sales']['tax'] - $row['purchases']['tax']) >= 0 ? 'text-danger' : 'text-success' }}">{{ number_format($row['sales']['tax'] - $row['purchases']['tax'], 2) }}</td><td>{{ $row['sales']['documents'] + $row['purchases']['documents'] }}</td></tr>@empty<tr><td colspan="8" class="text-center">No approved tax activity found for this period.</td></tr>@endforelse
    </tbody></table></div></div></div>
</div></div>
<div class="mt-2"><form method="GET" action="{{ route('erp.accounting.tax-report.export') }}" class="d-inline"><input type="hidden" name="from" value="{{ $from }}"><input type="hidden" name="to" value="{{ $to }}"><input type="hidden" name="jurisdiction" value="{{ $jurisdiction }}"><button class="btn btn-outline-secondary btn-sm">Export CSV</button></form></div>
@endsection
