@extends('admin.admin_master')
@section('admin')
<div class="page-content"><div class="container-fluid">
    <div class="page-title-box"><h4>Warranty Claims</h4><p class="text-muted">Register, review, settle, and audit warranty issues against service assets.</p></div>
    @if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
    <div class="card mb-3"><div class="card-body"><form method="POST" action="{{ route('erp.service.warranty.claims.store') }}">@csrf
        <div class="row g-2"><div class="col-md-3"><select name="asset_id" class="form-select" required><option value="">Asset</option>@foreach($assets as $asset)<option value="{{ $asset->id }}">{{ $asset->asset_no }} — {{ $asset->name }} @if($asset->warranty_until)({{ $asset->warranty_until->format('Y-m-d') }})@endif</option>@endforeach</select></div><div class="col-md-2"><select name="supplier_id" class="form-select"><option value="">Vendor (optional)</option>@foreach($suppliers as $supplier)<option value="{{ $supplier->id }}">{{ $supplier->name }}</option>@endforeach</select></div><div class="col-md-2"><input name="claim_no" class="form-control" placeholder="Claim no (optional)"></div><div class="col-md-2"><input name="received_at" type="date" value="{{ now()->toDateString() }}" class="form-control" required></div><div class="col-md-2"><input name="issue" class="form-control" placeholder="Issue description" required></div><div class="col-md-1"><button class="btn btn-primary">Submit</button></div></div>
    </form></div></div>
    <div class="card"><div class="card-body table-responsive"><table class="table table-bordered align-middle"><thead><tr><th>Claim</th><th>Asset / Contract</th><th>Customer</th><th>Received</th><th>Issue</th><th>Status / Decision</th><th>Settlement</th></tr></thead><tbody>
    @forelse($claims as $claim)<tr><td>{{ $claim->claim_no }}</td><td>{{ $claim->asset->asset_no }} — {{ $claim->asset->name }}<br>@if($claim->contract)<small class="text-muted">Contract: {{ $claim->contract->contract_no }}</small>@endif @if($claim->supplier)<br><small class="text-muted">Vendor: {{ $claim->supplier->name }}</small>@endif</td><td>{{ $claim->customer->name ?? '—' }}</td><td>{{ optional($claim->received_at)->format('Y-m-d') }}</td><td>{{ $claim->issue }}</td><td>{{ ucfirst(str_replace('_', ' ', $claim->status)) }}<br>{{ is_null($claim->covered) ? 'Coverage pending' : ($claim->covered ? 'Covered' : 'Not covered') }}
        @if($claim->settlement_status !== 'settled' && !in_array($claim->status, ['resolved', 'rejected'], true))<form method="POST" action="{{ route('erp.service.warranty.claims.decision', $claim->id) }}" class="mt-2">@csrf<select name="status" class="form-select form-select-sm mb-1">@foreach(['under_review','approved','rejected','resolved'] as $status)<option value="{{ $status }}" @selected($claim->status === $status)>{{ ucfirst(str_replace('_', ' ', $status)) }}</option>@endforeach</select><select name="covered" class="form-select form-select-sm mb-1"><option value="">Coverage unchanged</option><option value="1">Covered</option><option value="0">Not covered</option></select><textarea name="decision_notes" class="form-control form-control-sm mb-1" rows="2" placeholder="Decision notes">{{ $claim->decision_notes }}</textarea><button class="btn btn-sm btn-outline-primary">Save decision</button></form>@endif
    </td><td>@if($claim->settlement_status === 'settled')<span class="badge bg-success">Settled</span><br>{{ $claim->settlement_reference }}<br>{{ $claim->settlement_currency }} {{ number_format((float) $claim->settlement_amount, 2) }}<br><small>{{ str_replace('_', ' ', $claim->accounting_status) }}</small>@elseif(in_array($claim->status, ['approved','resolved'], true) && $claim->covered)<form method="POST" action="{{ route('erp.service.warranty.claims.settle', $claim->id) }}">@csrf<input name="settlement_reference" class="form-control form-control-sm mb-1" placeholder="Settlement reference" required><input name="settlement_amount" type="number" step="0.01" min="0" class="form-control form-control-sm mb-1" placeholder="Amount" required><input name="settlement_currency" value="{{ optional(auth()->user()->company)->base_currency ?? 'USD' }}" class="form-control form-control-sm mb-1" maxlength="3" required><select name="accounting_mode" class="form-select form-select-sm mb-1"><option value="none">Do not post accounting</option><option value="customer_reimbursement">Customer reimbursement</option><option value="vendor_recovery">Vendor recovery</option></select><button class="btn btn-sm btn-outline-success">Settle claim</button></form>@else<span class="text-muted">Decision required</span>@endif</td></tr>@empty<tr><td colspan="7" class="text-center">No warranty claims.</td></tr>@endforelse</tbody></table>{{ $claims->links() }}</div></div>
</div></div>
@endsection
