@extends('admin.admin_master')
@section('admin')
<div class="page-content"><div class="container-fluid"><div class="page-title-box"><h4>Supplier Purchase Invoice</h4><p class="text-muted">Invoice quantities are checked against approved goods receipts before posting AP.</p></div><div class="card"><div class="card-body"><form method="POST" action="{{ route('procurement.invoices.store') }}">@csrf<div class="row g-3 mb-3"><div class="col-md-3"><label>Invoice no.</label><input name="invoice_no" class="form-control" value="{{ old('invoice_no', 'PINV-'.now()->format('YmdHis')) }}" required></div><div class="col-md-4"><label>Purchase order</label><select name="purchase_order_id" class="form-select" required><option value="">Select PO</option>@foreach($orders as $order)<option value="{{ $order->id }}">{{ $order->po_no }} — {{ $order->supplier->name }}</option>@endforeach</select></div><div class="col-md-2"><label>Invoice date</label><input name="invoice_date" type="date" value="{{ now()->toDateString() }}" class="form-control" required></div><div class="col-md-3"><label>Due date</label><input name="due_date" type="date" class="form-control"></div></div><div class="table-responsive"><table class="table" id="pinv-lines"><thead><tr><th>Received PO line</th><th>Invoice qty</th><th>Unit price</th><th>Tax %</th><th></th></tr></thead><tbody><tr><td><select name="line_id[]" class="form-select" required><option value="">Select PO line</option>@foreach($orders as $order)@foreach($order->lines as $line)<option value="{{ $line->id }}">{{ $order->po_no }} — {{ $line->product->name }} (received {{ $line->received_qty }})</option>@endforeach @endforeach</select></td><td><input name="quantity[]" type="number" min="0.000001" step="0.000001" class="form-control" required></td><td><input name="unit_price[]" type="number" min="0" step="0.000001" class="form-control" required></td><td><input name="tax_rate[]" type="number" min="0" max="100" step="0.01" value="0" class="form-control"></td><td><button type="button" class="btn btn-outline-danger remove-line">Remove</button></td></tr></tbody></table></div><button type="button" id="add-line" class="btn btn-light">Add line</button> <button class="btn btn-primary">Submit invoice</button></form></div></div></div></div><script>document.getElementById('add-line').addEventListener('click',function(){const row=document.querySelector('#pinv-lines tbody tr').cloneNode(true);row.querySelectorAll('input').forEach(i=>i.value=i.name==='tax_rate[]'?'0':'');row.querySelectorAll('select').forEach(s=>s.selectedIndex=0);document.querySelector('#pinv-lines tbody').appendChild(row);});document.addEventListener('click',function(e){if(e.target.classList.contains('remove-line')&&document.querySelectorAll('#pinv-lines tbody tr').length>1)e.target.closest('tr').remove();});</script>
<script>
const purchaseInvoiceForm = document.querySelector('form[action="{{ route('procurement.invoices.store') }}"]');
if (purchaseInvoiceForm) {
    const row = document.createElement('div');
    row.className = 'row g-2 mb-3';
    row.innerHTML = '<div class="col-md-2"><label>Currency</label><input name="currency_code" value="{{ auth()->user()?->company?->base_currency ?? 'USD' }}" maxlength="3" class="form-control"></div><div class="col-md-2"><label>Rate to base</label><input name="exchange_rate" type="number" min="0.000001" step="0.000001" value="" placeholder="Auto lookup" class="form-control"></div><div class="col-md-2"><label>Tax mode</label><select name="tax_mode" class="form-select"><option value="exclusive" @selected($defaultTaxMode === "exclusive")>Exclusive</option><option value="inclusive" @selected($defaultTaxMode === "inclusive")>Inclusive</option></select></div>';
    purchaseInvoiceForm.prepend(row);
}
</script>
@endsection
