@extends('admin.admin_master')
@section('admin')
<div class="container-fluid mt-3">
    <div class="page-title-box"><h4>Supplier Corrective Actions</h4><p class="text-muted">Track supplier quality, delivery, and commercial issues through auditable resolution.</p><div class="d-flex gap-3"><span class="badge bg-secondary">Total: {{ $summary['total'] }}</span><span class="badge bg-warning text-dark">Open: {{ $summary['open'] }}</span><span class="badge bg-info text-dark">In progress: {{ $summary['in_progress'] }}</span><span class="badge bg-danger">Overdue: {{ $summary['overdue'] }}</span></div></div>
    @if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
    <div class="card mb-3"><div class="card-body"><form method="POST" action="{{ route('procurement.supplier.corrective.store') }}" class="row g-2 align-items-end">@csrf
        <div class="col-md-2"><label>Supplier</label><select name="supplier_id" class="form-select" required><option value="">Select</option>@foreach($suppliers as $supplier)<option value="{{ $supplier->id }}">{{ $supplier->name }}</option>@endforeach</select></div>
        <div class="col-md-2"><label>Title</label><input name="title" class="form-control" required></div><div class="col-md-2"><label>Issue type</label><input name="issue_type" class="form-control" placeholder="delivery" required></div>
        <div class="col-md-1"><label>Severity</label><select name="severity" class="form-select"><option>low</option><option selected>medium</option><option>high</option><option>critical</option></select></div><div class="col-md-2"><label>Due date</label><input type="date" name="due_date" class="form-control"></div>
        <div class="col-md-2"><label>Owner</label><select name="owner_id" class="form-select"><option value="">Unassigned</option>@foreach($users as $user)<option value="{{ $user->id }}">{{ $user->name }}</option>@endforeach</select></div><div class="col-md-1"><button class="btn btn-primary">Create</button></div>
        <div class="col-md-12"><label>Description</label><textarea name="description" class="form-control" rows="2"></textarea></div>
    </form></div></div>
    <form method="GET" class="row g-2 mb-3"><div class="col-md-3"><select name="supplier_id" class="form-select"><option value="">All suppliers</option>@foreach($suppliers as $supplier)<option value="{{ $supplier->id }}" @selected((string)($filters['supplier_id'] ?? '') === (string)$supplier->id)>{{ $supplier->name }}</option>@endforeach</select></div><div class="col-md-2"><select name="status" class="form-select"><option value="">All statuses</option>@foreach(['open','in_progress','resolved','closed'] as $status)<option @selected(($filters['status'] ?? '') === $status)>{{ $status }}</option>@endforeach</select></div><div class="col-md-2"><select name="severity" class="form-select"><option value="">All severities</option>@foreach(['low','medium','high','critical'] as $severity)<option @selected(($filters['severity'] ?? '') === $severity)>{{ $severity }}</option>@endforeach</select></div><div class="col-md-2"><button class="btn btn-outline-primary">Filter</button></div></form>
    <div class="card"><div class="card-body"><div class="table-responsive"><table class="table table-bordered"><thead><tr><th>Supplier</th><th>Issue</th><th>Severity</th><th>Due</th><th>Owner</th><th>Status / resolution</th><th>Save</th></tr></thead><tbody>@forelse($actions as $action)<tr><td>{{ $action->supplier?->name }}</td><td><strong>{{ $action->title }}</strong><br><small>{{ $action->issue_type }}</small><br>{{ $action->description }}</td><td>{{ $action->severity }}</td><td>{{ optional($action->due_date)->toDateString() ?: '—' }}</td><td>{{ $action->owner?->name ?: 'Unassigned' }}</td><td><form method="POST" action="{{ route('procurement.supplier.corrective.update', $action->id) }}">@csrf @method('PATCH')<select name="status" class="form-select form-select-sm mb-1">@foreach(['open','in_progress','resolved','closed'] as $status)<option @selected($action->status === $status)>{{ $status }}</option>@endforeach</select><textarea name="resolution" class="form-control form-control-sm" rows="2" placeholder="Resolution required to close">{{ $action->resolution }}</textarea></td><td><button class="btn btn-sm btn-success">Save</button></form></td></tr>@empty<tr><td colspan="7" class="text-center">No corrective actions found.</td></tr>@endforelse</tbody></table></div>{{ $actions->links() }}</div></div>
</div>
@endsection
