@extends('admin.admin_master')
@section('admin')
<div class="page-content"><div class="container-fluid"><div class="page-title-box"><h4>Supplier Contacts & Addresses</h4></div>
<div class="card mb-3"><div class="card-body"><form method="POST" action="{{ route('supplier.contacts.store') }}" class="row g-2">@csrf
<div class="col-md-2"><select name="supplier_id" class="form-select" required><option value="">Supplier</option>@foreach($suppliers as $supplier)<option value="{{ $supplier->id }}">{{ $supplier->name }}</option>@endforeach</select></div>
<div class="col-md-2"><select name="contact_type" class="form-select" required><option value="shipping">Shipping</option><option value="billing">Billing</option><option value="contact">Contact</option></select></div>
<div class="col-md-2"><input name="contact_name" class="form-control" placeholder="Contact name"></div><div class="col-md-2"><input name="phone" class="form-control" placeholder="Phone"></div><div class="col-md-2"><input name="email" type="email" class="form-control" placeholder="Email"></div><div class="col-md-2"><input name="label" class="form-control" placeholder="Label"></div>
<div class="col-md-4"><input name="line1" class="form-control" placeholder="Address line 1"></div><div class="col-md-3"><input name="line2" class="form-control" placeholder="Address line 2"></div><div class="col-md-2"><input name="city" class="form-control" placeholder="City"></div><div class="col-md-2"><input name="state" class="form-control" placeholder="State"></div><div class="col-md-1"><input name="postal_code" class="form-control" placeholder="PIN"></div><div class="col-md-1"><input name="country" value="IN" maxlength="2" class="form-control" placeholder="CC"></div>
<div class="col-md-2 form-check ms-2"><input name="is_default" value="1" type="checkbox" class="form-check-input" id="supplier-default"><label for="supplier-default" class="form-check-label">Default</label></div><div class="col-md-2"><button class="btn btn-primary">Save contact</button></div></form></div></div>
<div class="card"><div class="card-body"><div class="table-responsive"><table class="table table-bordered"><thead><tr><th>Supplier</th><th>Type</th><th>Contact</th><th>Phone/email</th><th>Address</th><th>Default</th><th>Action</th></tr></thead><tbody>@forelse($contacts as $contact)<tr><td>{{ $contact->supplier->name }}</td><td>{{ ucfirst($contact->contact_type) }}</td><td>{{ $contact->contact_name ?: '—' }}</td><td>{{ $contact->phone ?: '—' }}<br>{{ $contact->email ?: '' }}</td><td>{{ implode(', ', array_filter([$contact->line1, $contact->line2, $contact->city, $contact->state, $contact->postal_code])) }}</td><td>{{ $contact->is_default ? 'Yes' : 'No' }}</td><td><details><summary class="btn btn-sm btn-outline-secondary">Edit</summary><form method="POST" action="{{ route('supplier.contacts.update', $contact->id) }}" class="mt-2">@csrf @method('PATCH')<select name="contact_type" class="form-select mb-1"><option value="shipping" @selected($contact->contact_type === 'shipping')>Shipping</option><option value="billing" @selected($contact->contact_type === 'billing')>Billing</option><option value="contact" @selected($contact->contact_type === 'contact')>Contact</option></select><input name="contact_name" class="form-control mb-1" value="{{ $contact->contact_name }}" placeholder="Contact name"><input name="phone" class="form-control mb-1" value="{{ $contact->phone }}" placeholder="Phone"><input name="email" type="email" class="form-control mb-1" value="{{ $contact->email }}" placeholder="Email"><input name="line1" class="form-control mb-1" value="{{ $contact->line1 }}" placeholder="Address line 1"><input name="city" class="form-control mb-1" value="{{ $contact->city }}" placeholder="City"><input name="state" class="form-control mb-1" value="{{ $contact->state }}" placeholder="State"><input name="postal_code" class="form-control mb-1" value="{{ $contact->postal_code }}" placeholder="PIN"><input name="country" maxlength="2" class="form-control mb-1" value="{{ $contact->country }}" placeholder="CC"><label><input name="is_default" value="1" type="checkbox" @checked($contact->is_default)> Default</label><button class="btn btn-primary btn-sm mt-1">Save</button></form></details></td></tr>@empty<tr><td colspan="7" class="text-center">No supplier contacts found.</td></tr>@endforelse</tbody></table></div>{{ $contacts->links() }}</div></div></div></div>
@endsection
